version: '3'
services:
  db:
    container_name: db
    image: mysql:5.7
    ports:
    - "33061:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: recipes
  api:
    container_name: rails
    build: ./rails
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
    - "3000:3000"
    depends_on:
    - db
  front:
    container_name: vue
    build: ./vue
    command: npm run serve
    ports:
    - "8081:8080"